<?php

/*####################################################*\
#   CS5248       NUS School of Computing        2017   #
#                     DASH Project                     #
#                  Task 2: Server side                 #
#                                                      #
#                 By:   Loïc PERACHE                   #
#                       perache@comp.nus.edu           #
#                       A0174362E                      #
\*####################################################*/

/*
* This file is used to create a new video on the server, its called before sending any part of the video
*/

// This page expects a POST request with a JSON containing 'title' and 'desctiption' of the video to be uploaded, it returns a unique ID of the video


/* Verify that the input is correct */

$is_JSON = True;

// Make sure that it is a POST request
if(strcasecmp($_SERVER['REQUEST_METHOD'], 'POST') != 0){
	echo "Request method must be POST!<br>";
	$is_JSON = False;
}
 
// Make sure that the content type of the POST request has been set to application/json
$contentType = isset($_SERVER["CONTENT_TYPE"]) ? trim($_SERVER["CONTENT_TYPE"]) : '';
if(strcasecmp($contentType, 'application/json') != 0){
	echo "Content type must be: application/json<br>";
	$is_JSON = False;
}

// Decode the JASON
if ($is_JSON){
	$data = json_decode(file_get_contents('php://input'), true);
	$title = $data["title"];
	$description = $data["description"];
}


//TODO: Remove the 2 lines it's only for testing
/*
$title="my-video";
$description="this is fine";
*/

// Adding this upload to the log
$IP_address = $_SERVER['REMOTE_ADDR'];
$user_agent = $_SERVER['HTTP_USER_AGENT'];
$log_file = "log/new.txt";
$current_log = file_get_contents($log_file);
$time = date("Y-m-d h:i:sa");
$current_log .= $time ." : File name ". $name . " status " . $is_JSON ." from IP: ".$IP_address."\n\tThe user used: ".$user_agent ."\n";
file_put_contents($log_file,$current_log);


/* Now that we have all the information we add the video to the database */

// We add the entry in the data base and create the playlist
if ($is_JSON){
	$servername = "localhost";
	$username = "team05";
	$password = "bestteam05!";
	$databasename = "team05";
	// Create connection
	$conn = new mysqli($servername, $username, $password,$databasename);
	if ($conn->connect_error) {
	   die("Connection failed =/ \n" . $conn->connect_error);
	}
	// We add the video with the given title and description
	$txt = "INSERT INTO `information_table`(`title`, `description`) VALUES (\"" . $title . "\",\"" . $description . "\");";
	// We return the unique video ID generated by the database
	$txt .= "SELECT `ID` FROM `information_table` WHERE `title`=\"" . $title . "\" AND `description`=\"" . $description . "\"";
	if ($conn->multi_query($txt)) {
	    do {
		/* Stockage du premier résultat */
		if ($result = $conn->store_result()) {
		    while ($row = $result->fetch_row()) {
			$ID = $row[0];
		    }
		    $result->free();
		}
	    } while ($conn->next_result());
	}
	$conn->close();
	//We return the video ID we got from the data base to our client
	echo $ID;
        //create the playlist file in m3u8 
	create_m3u8($ID);
}
else{
	echo "Error: Abort mission no data base entry was created<br>";
}


/* This is the function creating the playlist file in m3u8 */

function create_m3u8($ID){
	$file = 'playlist/' . $ID . '.m3u8';
	$current = file_get_contents($file);
	$txt="#EXTM3U\n#EXT-X-STREAM-INF:PROGRAM-ID=1, BANDWIDTH=700000\n../uploads/" . $ID . "/" . $ID;
	$txt .="-low.m3u8\n#EXT-X-STREAM-INF:PROGRAM-ID=1, BANDWIDTH=1000000\n../uploads/";
	$txt .= $ID . "/" . $ID . "-medium.m3u8\n#EXT-X-STREAM-INF:PROGRAM-ID=1, BANDWIDTH=2000000\n../uploads/" . $ID . "/" . $ID . "-high.m3u8\n";
	$current .= $txt;
	file_put_contents($file, $current);
}
?>
